### ISSUE TITLE
add GH action to push version releases to the vscode marketplace automatically

### ISSUE THREAD

**Issue by andrewkern** [slim-community/slim-vscode-tools#7]
This should be simple enough. The idea is to set up an action with a GH workflow that pushes to the microsoft vscode marketplace automatically. 

This would require putting my personal access token (PAT) in a GH secret like:

`VSCE_TOKEN: <PAT>`

A draft for the action would be like:

```yaml
name: Publish VSCode Extension

on:
  push:
    tags:
      - 'v*'  # triggers on version tags like v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - run: npm ci

    - run: npm install -g vsce

    - run: vsce publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
```
